name: Windows Server 2019

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
    - uses: actions/checkout@v3
    - name: auto exec
      run: ./win10pro.ps1
